version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - REACT_APP_API_HOST=https://api.darisly.com/v1 npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
